name: SEU Auto Leave
on:
  push:
    branches:
      - master
  schedule:
    - cron: '05 22 * * *'
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天UTC时间的22点05分整， 北京时间的06点05分（24小时制）
    # 可在此网站查询UTC时间和北京时间的换算关系 https://datetime360.com/cn/utc-beijing-time/

jobs:
  Leave:
    name: Checkout Repository
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      env:
        TZ: Asia/Shanghai
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install python3-setuptools -y
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: do report
      run: |
        python ./main.py
